export const SOUND_MARK_PATTERN_IDS = [
  "dakuten-k",
  "dakuten-s",
  "dakuten-t",
  "dakuten-h",
  "handakuten-h",
  "sound-hiragana-gi",
  "sound-hiragana-gu",
  "sound-hiragana-ge",
  "sound-hiragana-go",
  "sound-hiragana-ji",
  "sound-hiragana-zu",
  "sound-hiragana-ze",
  "sound-hiragana-zo",
  "sound-hiragana-di",
  "sound-hiragana-du",
  "sound-hiragana-de",
  "sound-hiragana-do",
  "sound-hiragana-bi",
  "sound-hiragana-bu",
  "sound-hiragana-be",
  "sound-hiragana-bo",
  "sound-hiragana-pi",
  "sound-hiragana-pu",
  "sound-hiragana-pe",
  "sound-hiragana-po",
  "sound-katakana-ga",
  "sound-katakana-gi",
  "sound-katakana-gu",
  "sound-katakana-ge",
  "sound-katakana-go",
  "sound-katakana-za",
  "sound-katakana-ji",
  "sound-katakana-zu",
  "sound-katakana-ze",
  "sound-katakana-zo",
  "sound-katakana-da",
  "sound-katakana-di",
  "sound-katakana-du",
  "sound-katakana-de",
  "sound-katakana-do",
  "sound-katakana-ba",
  "sound-katakana-bi",
  "sound-katakana-bu",
  "sound-katakana-bo",
  "sound-katakana-pa",
  "sound-katakana-pi",
  "sound-katakana-pu",
  "sound-katakana-po",
] as const;

export const COMBINED_SOUND_PATTERN_IDS = [
  "small-kya",
  "small-shu",
  "small-cho",
  "small-nyu",
  "small-ryo",
  "yoon-hiragana-kyu",
  "yoon-hiragana-kyo",
  "yoon-hiragana-sha",
  "yoon-hiragana-sho",
  "yoon-hiragana-cha",
  "yoon-hiragana-chu",
  "yoon-hiragana-nya",
  "yoon-hiragana-nyo",
  "yoon-hiragana-hya",
  "yoon-hiragana-hyu",
  "yoon-hiragana-hyo",
  "yoon-hiragana-mya",
  "yoon-hiragana-myu",
  "yoon-hiragana-myo",
  "yoon-hiragana-rya",
  "yoon-hiragana-ryu",
  "yoon-hiragana-gya",
  "yoon-hiragana-gyu",
  "yoon-hiragana-gyo",
  "yoon-hiragana-ja",
  "yoon-hiragana-ju",
  "yoon-hiragana-jo",
  "yoon-hiragana-bya",
  "yoon-hiragana-byu",
  "yoon-hiragana-byo",
  "yoon-hiragana-pya",
  "yoon-hiragana-pyu",
  "yoon-hiragana-pyo",
  "yoon-katakana-kya",
  "yoon-katakana-kyu",
  "yoon-katakana-kyo",
  "yoon-katakana-sha",
  "yoon-katakana-shu",
  "yoon-katakana-sho",
  "yoon-katakana-cha",
  "yoon-katakana-chu",
  "yoon-katakana-cho",
  "yoon-katakana-nya",
  "yoon-katakana-nyu",
  "yoon-katakana-nyo",
  "yoon-katakana-hya",
  "yoon-katakana-hyu",
  "yoon-katakana-hyo",
  "yoon-katakana-mya",
  "yoon-katakana-myu",
  "yoon-katakana-myo",
  "yoon-katakana-rya",
  "yoon-katakana-ryu",
  "yoon-katakana-ryo",
  "yoon-katakana-gya",
  "yoon-katakana-gyu",
  "yoon-katakana-gyo",
  "yoon-katakana-ja",
  "yoon-katakana-ju",
  "yoon-katakana-jo",
  "yoon-katakana-bya",
  "yoon-katakana-byu",
  "yoon-katakana-byo",
  "yoon-katakana-pya",
  "yoon-katakana-pyu",
  "yoon-katakana-pyo",
] as const;

export const KANA_EXTENSION_PATTERN_IDS = [
  ...SOUND_MARK_PATTERN_IDS,
  ...COMBINED_SOUND_PATTERN_IDS,
] as const;

export type KanaExtensionPatternId = (typeof KANA_EXTENSION_PATTERN_IDS)[number];

const KANA_EXTENSION_PATTERN_ID_SET = new Set<string>(KANA_EXTENSION_PATTERN_IDS);

export function isKanaExtensionPatternId(
  value: unknown,
): value is KanaExtensionPatternId {
  return typeof value === "string" && KANA_EXTENSION_PATTERN_ID_SET.has(value);
}
