export type TravelPhrase = {
  readonly audio: `/audio/${string}.wav`;
  readonly id: string;
  readonly japanese: string;
  readonly japaneseSegments?: readonly string[];
  readonly meaning: string;
  readonly note?: string;
  readonly romaji?: string;
  readonly source: string;
};

export type TravelPhraseStation =
  | "food"
  | "help"
  | "introductions"
  | "navigation"
  | "shopping";

export const TRAVEL_ORIENTATION = {
  japanese: {
    audio: "/audio/ja-travel-nihongo.wav",
    japanese: "日本語",
    meaning: "Japanese",
  },
  japan: {
    audio: "/audio/ja-travel-nihon.wav",
    japanese: "日本",
    meaning: "Japan",
  },
} as const;

export const JAPAN_STARTER_PHRASES: readonly TravelPhrase[] = [
  {
    id: "sumimasen",
    japanese: "すみません",
    meaning: "Excuse me / I’m sorry",
    note: "Also useful for getting someone’s attention.",
    romaji: "Sumimasen",
    audio: "/audio/ja-travel-sumimasen.wav",
    source: "JNTO Japanese language basics and etiquette guidance",
  },
  {
    id: "arigatou-gozaimasu",
    japanese: "ありがとうございます",
    meaning: "Thank you",
    note: "Polite and broadly useful.",
    romaji: "Arigatō gozaimasu",
    audio: "/audio/ja-travel-arigatou-gozaimasu.wav",
    source: "JNTO Japanese language basics",
  },
  {
    id: "onegaishimasu",
    japanese: "お願いします",
    meaning: "Please",
    note: "Use when making or confirming a request.",
    romaji: "Onegaishimasu",
    audio: "/audio/ja-travel-onegaishimasu.wav",
    source: "Irodori Starter request patterns",
  },
] as const;

export const TRAVEL_PHRASES: Readonly<
  Record<TravelPhraseStation, readonly TravelPhrase[]>
> = {
  help: [
    {
      id: "tasukete-kudasai",
      japanese: "助けてください",
      meaning: "Please help me.",
      romaji: "Tasukete kudasai.",
      audio: "/audio/ja-travel-tasukete-kudasai.wav",
      source: "Irodori emergency assistance patterns",
    },
    {
      id: "kibun-ga-warui-desu",
      japanese: "気分が悪いです",
      meaning: "I feel sick.",
      romaji: "Kibun ga warui desu.",
      audio: "/audio/ja-travel-kibun-ga-warui-desu.wav",
      source: "JNTO medical assistance guidance",
    },
    {
      id: "koko-ga-itai-desu",
      japanese: "ここが痛いです",
      meaning: "It hurts here.",
      note: "Point to where it hurts.",
      romaji: "Koko ga itai desu.",
      audio: "/audio/ja-travel-koko-ga-itai-desu.wav",
      source: "Japan Tourism Agency medical communication guide",
    },
    {
      id: "kyuukyuusha-o-yonde-kudasai",
      japanese: "救急車を呼んでください",
      japaneseSegments: ["救急車を", "呼んでください"],
      meaning: "Please call an ambulance.",
      romaji: "Kyūkyūsha o yonde kudasai.",
      audio: "/audio/ja-travel-kyuukyuusha-o-yonde-kudasai.wav",
      source: "Irodori Pre-Intermediate L12",
    },
    {
      id: "keisatsu-o-yonde-kudasai",
      japanese: "警察を呼んでください",
      japaneseSegments: ["警察を", "呼んでください"],
      meaning: "Please call the police.",
      romaji: "Keisatsu o yonde kudasai.",
      audio: "/audio/ja-travel-keisatsu-o-yonde-kudasai.wav",
      source: "Irodori Pre-Intermediate L12",
    },
    {
      id: "byouin-wa-doko-desu-ka",
      japanese: "病院はどこですか？",
      meaning: "Where is the hospital?",
      romaji: "Byōin wa doko desu ka?",
      audio: "/audio/ja-travel-byouin-wa-doko-desu-ka.wav",
      source: "JNTO medical assistance guidance",
    },
    {
      id: "pasupooto-o-nakushimashita",
      japanese: "パスポートをなくしました",
      japaneseSegments: ["パスポートを", "なくしました"],
      meaning: "I lost my passport.",
      romaji: "Pasupōto o nakushimashita.",
      audio: "/audio/ja-travel-pasupooto-o-nakushimashita.wav",
      source: "JNTO lost passport guidance",
    },
    {
      id: "eigo-o-hanaseru-hito-wa-imasu-ka",
      japanese: "英語を話せる人はいますか？",
      japaneseSegments: ["英語を話せる人は", "いますか？"],
      meaning: "Is there someone who speaks English?",
      romaji: "Eigo o hanaseru hito wa imasu ka?",
      audio: "/audio/ja-travel-eigo-o-hanaseru-hito-wa-imasu-ka.wav",
      source: "Irodori language assistance pattern",
    },
  ],
  introductions: [
    {
      id: "hajimemashite-kurisu-desu",
      japanese: "はじめまして、クリスです",
      japaneseSegments: ["はじめまして、", "クリスです"],
      meaning: "Nice to meet you. I’m Chris.",
      romaji: "Hajimemashite, Kurisu desu.",
      audio: "/audio/ja-travel-hajimemashite-kurisu-desu.wav",
      source: "Irodori Starter L3 self-introduction model",
    },
    {
      id: "yoroshiku-onegaishimasu",
      japanese: "よろしくお願いします",
      meaning: "It’s a pleasure to meet you.",
      romaji: "Yoroshiku onegaishimasu.",
      audio: "/audio/ja-travel-yoroshiku-onegaishimasu.wav",
      source: "Irodori Starter L3 self-introduction model",
    },
    {
      id: "goshusshin-wa",
      japanese: "ご出身は？",
      meaning: "Where are you from?",
      romaji: "Goshusshin wa?",
      audio: "/audio/ja-travel-goshusshin-wa.wav",
      source: "Irodori Starter L3 first-meeting question",
    },
    {
      id: "amerika-kara-kimashita",
      japanese: "アメリカから来ました",
      meaning: "I’m from the United States.",
      note: "Answer with your country or hometown.",
      romaji: "Amerika kara kimashita.",
      audio: "/audio/ja-travel-amerika-kara-kimashita.wav",
      source: "Irodori Starter L3 self-introduction model",
    },
    {
      id: "nihongo-dekimasu-ka",
      japanese: "日本語、できますか？",
      meaning: "Do you speak Japanese?",
      romaji: "Nihongo, dekimasu ka?",
      audio: "/audio/ja-travel-nihongo-dekimasu-ka.wav",
      source: "Irodori Starter L2 language ability question",
    },
    {
      id: "hai-sukoshi-dekimasu",
      japanese: "はい、少しできます",
      meaning: "Yes, a little.",
      romaji: "Hai, sukoshi dekimasu.",
      audio: "/audio/ja-travel-hai-sukoshi-dekimasu.wav",
      source: "Irodori Starter L2 language ability response",
    },
    {
      id: "eigo-dekimasu-ka",
      japanese: "英語、できますか？",
      meaning: "Do you speak English?",
      romaji: "Eigo, dekimasu ka?",
      audio: "/audio/ja-travel-eigo-dekimasu-ka.wav",
      source: "Irodori Starter L2 language ability question pattern",
    },
    {
      id: "hai-dekimasu",
      japanese: "はい、できます",
      meaning: "Yes, I do.",
      romaji: "Hai, dekimasu.",
      audio: "/audio/ja-travel-hai-dekimasu.wav",
      source: "Irodori Starter L2 language ability response",
    },
  ],
  navigation: [
    {
      id: "toire-wa-doko-desu-ka",
      japanese: "トイレはどこですか？",
      meaning: "Where is the restroom?",
      romaji: "Toire wa doko desu ka?",
      audio: "/audio/ja-travel-toire-wa-doko-desu-ka.wav",
      source: "JNTO Japanese language basics",
    },
    {
      id: "nanban-sen-desu-ka",
      japanese: "何番線ですか？",
      meaning: "Which platform?",
      romaji: "Nanbansen desu ka?",
      audio: "/audio/ja-travel-nanban-sen-desu-ka.wav",
      source: "Irodori Starter L13",
    },
    {
      id: "koko-made-onegaishimasu",
      japanese: "ここまでお願いします",
      japaneseSegments: ["ここまで", "お願いします"],
      meaning: "To here, please",
      note: "Show a map or address to a taxi driver.",
      romaji: "Koko made onegaishimasu.",
      audio: "/audio/ja-travel-koko-made-onegaishimasu.wav",
      source: "Irodori destination and request patterns",
    },
    {
      id: "kono-densha-de-atteimasu-ka",
      japanese: "この電車で合っていますか？",
      japaneseSegments: ["この電車で", "合っていますか？"],
      meaning: "Is this the right train?",
      romaji: "Kono densha de atteimasu ka?",
      audio: "/audio/ja-travel-kono-densha-de-atteimasu-ka.wav",
      source: "Irodori transport confirmation pattern",
    },
    {
      id: "doko-de-norikaemasu-ka",
      japanese: "どこで乗り換えますか？",
      japaneseSegments: ["どこで", "乗り換えますか？"],
      meaning: "Where do I transfer?",
      romaji: "Doko de norikaemasu ka?",
      audio: "/audio/ja-travel-doko-de-norikaemasu-ka.wav",
      source: "Irodori transport transfer pattern",
    },
    {
      id: "nanban-deguchi-desu-ka",
      japanese: "何番出口ですか？",
      meaning: "Which exit?",
      romaji: "Nanban deguchi desu ka?",
      audio: "/audio/ja-travel-nanban-deguchi-desu-ka.wav",
      source: "Irodori station exit pattern",
    },
  ],
  food: [
    {
      id: "futari-desu",
      japanese: "二人です",
      meaning: "There are two of us.",
      romaji: "Futari desu.",
      audio: "/audio/ja-travel-futari-desu.wav",
      source: "Irodori Elementary 2 L3 restaurant entry dialog",
    },
    {
      id: "yoyaku-shiteimasu",
      japanese: "予約しています",
      meaning: "I have a reservation.",
      romaji: "Yoyaku shiteimasu.",
      audio: "/audio/ja-travel-yoyaku-shiteimasu.wav",
      source: "Irodori Elementary 2 L3 restaurant entry dialog",
    },
    {
      id: "osusume-wa-nan-desu-ka",
      japanese: "おすすめは何ですか？",
      meaning: "What do you recommend?",
      romaji: "Osusume wa nan desu ka?",
      audio: "/audio/ja-travel-osusume-wa-nan-desu-ka.wav",
      source: "Irodori restaurant recommendation material",
    },
    {
      id: "kore-o-onegaishimasu",
      japanese: "これをお願いします",
      meaning: "This, please",
      note: "Point to the item while asking.",
      romaji: "Kore o onegaishimasu.",
      audio: "/audio/ja-travel-kore-o-onegaishimasu.wav",
      source: "Irodori request patterns",
    },
    {
      id: "omizu-o-onegaishimasu",
      japanese: "お水をお願いします",
      meaning: "Water, please",
      romaji: "Omizu o onegaishimasu.",
      audio: "/audio/ja-travel-omizu-o-onegaishimasu.wav",
      source: "JNTO Tourist's Language Handbook restaurant requests",
    },
    {
      id: "tamago-wa-haitteimasu-ka",
      japanese: "卵は入っていますか？",
      meaning: "Does this contain egg?",
      note: "Replace 卵 with the ingredient you need to check.",
      romaji: "Tamago wa haitte imasu ka?",
      audio: "/audio/ja-travel-tamago-wa-haitteimasu-ka.wav",
      source: "Irodori ingredient-check pattern",
    },
    {
      id: "okaikei-onegaishimasu",
      japanese: "お会計、お願いします",
      meaning: "The bill, please",
      romaji: "Okaikei, onegaishimasu.",
      audio: "/audio/ja-travel-okaikei-onegaishimasu.wav",
      source: "Irodori restaurant word list",
    },
    {
      id: "gochisousama-deshita",
      japanese: "ごちそうさまでした",
      meaning: "Thank you for the meal.",
      romaji: "Gochisōsama deshita.",
      audio: "/audio/ja-travel-gochisousama-deshita.wav",
      source: "JNTO Japanese dining etiquette guidance",
    },
  ],
  shopping: [
    {
      id: "kore-ikura-desu-ka",
      japanese: "これ、いくらですか？",
      meaning: "How much is this?",
      romaji: "Kore, ikura desu ka?",
      audio: "/audio/ja-travel-kore-ikura-desu-ka.wav",
      source: "Irodori Starter L16; JNTO Japanese language basics",
    },
    {
      id: "kore-o-kudasai",
      japanese: "これをください",
      meaning: "This, please",
      note: "Use when choosing an item to buy.",
      romaji: "Kore o kudasai.",
      audio: "/audio/ja-travel-kore-o-kudasai.wav",
      source: "Irodori Starter purchasing pattern",
    },
    {
      id: "hoka-no-iro-arimasu-ka",
      japanese: "ほかの色、ありますか？",
      meaning: "Do you have another color?",
      romaji: "Hoka no iro, arimasu ka?",
      audio: "/audio/ja-travel-hoka-no-iro-arimasu-ka.wav",
      source: "Irodori Elementary 2 L11",
    },
    {
      id: "hoka-no-saizu-arimasu-ka",
      japanese: "ほかのサイズ、ありますか？",
      meaning: "Do you have another size?",
      romaji: "Hoka no saizu, arimasu ka?",
      audio: "/audio/ja-travel-hoka-no-saizu-arimasu-ka.wav",
      source: "Irodori Elementary 2 L11",
    },
    {
      id: "shichaku-shite-mo-ii-desu-ka",
      japanese: "試着してもいいですか？",
      meaning: "May I try it on?",
      note: "For clothing.",
      romaji: "Shichaku shite mo ii desu ka?",
      audio: "/audio/ja-travel-shichaku-shite-mo-ii-desu-ka.wav",
      source: "Irodori Elementary 2 L11",
    },
    {
      id: "kaado-wa-tsukaemasu-ka",
      japanese: "カードは使えますか？",
      meaning: "Can I use a card?",
      romaji: "Kādo wa tsukaemasu ka?",
      audio: "/audio/ja-travel-kaado-wa-tsukaemasu-ka.wav",
      source: "Irodori payment contexts",
    },
    {
      id: "menzei-dekimasu-ka",
      japanese: "免税できますか？",
      meaning: "Can I buy this tax-free?",
      romaji: "Menzei dekimasu ka?",
      audio: "/audio/ja-travel-menzei-dekimasu-ka.wav",
      source: "JNTO tax-free shopping guidance",
    },
    {
      id: "fukuro-o-onegaishimasu",
      japanese: "袋をお願いします",
      meaning: "A bag, please",
      romaji: "Fukuro o onegaishimasu.",
      audio: "/audio/ja-travel-fukuro-o-onegaishimasu.wav",
      source: "Irodori shopping request pattern",
    },
  ],
};
